Fix auto biometric prompt on vault timeout
bitwarden/mobile pull request #1048
Opened 2020-08-22 12:20 UTC by aaxdev

A condition force to not show the auto biometric prompt (https://github.com/bitwarden/mobile/issues/1045).

This condition don't change the case about when you lock manually the vault from settings page or app bar, because the value of the function parameter is false in those cases, and the prompt is not shown, as expected.

However, in the case that the vault is not locked and you hit the home button or when you lock the phone screen, the value of the function parameter is true, and the condition set it on false, then the prompt will not be shown when you'll access back to the app. Whatever vault timeout selected, it's happen when the vault timed out. When it sets to "Immediatly" this behavior is annoying when you want to switch to another app and go back to it.

<details>
  <summary>GIF issue (expand)</summary>

![gif](https://i.gyazo.com/0a32a289e100f62ab74882ab2ee894f5.gif)
</details>

I don't get this issue on iOS version, it's maybe due to the sub condition vaultTimeout, i have always his value on null when i try it on Android but since i don't have any Mac environment, i can't debug it on iOS.

2020-12-12 12:55 UTC, aaxdev commented
any update?

2020-12-14 18:21 UTC, cscharf commented
@Hinton ☝🏻

2020-12-17 18:26 UTC, mportune-bw commented on src/App/App.xaml.cs
> -            if (autoPromptBiometric && Device.RuntimePlatform == Device.iOS)
For the moment let's leave this iOS if block in place.  I was able to trigger a race condition resulting in a double-prompt and everything went sideways (though I've only been able to do it once).  Go ahead and remove the Android else block though, as that seems to achieve the desired result.

2020-12-17 18:27 UTC, mportune-bw requested changes
See inline comment

2020-12-21 16:55 UTC, cscharf approved these changes

2020-12-21 17:15 UTC, merged