Attempt URI healing with https prior to http
bitwarden/mobile pull request #1186
Opened 2020-12-18 22:43 UTC by MGibson1

# Overview

Related to #1021. 

Browsers are moving away from displaying URI scheme in a way accessibility can easily grab. This causes this URI healing to be relied upon more frequently. It should attempt https prior to http due to prevelence of https and security concerns with passwords over http.

# Files changed

* **AccessibilityHelpers.cs**: This helper is responsible for grabbing the Uri out of  a browser's address node. If a URI scheme isn't present, it heals the URI with `https://`.  It seems unlikely that any URI that isn't healed by `https://` would be by prepending `http://`, but the attempt isn't very expensive.

2020-12-18 22:48 UTC, mportune-bw reviewed
Not sure I see the need to keep `http` as well.  Would there ever be a situation where a URI would fail to create with `https` but not `http`?

2020-12-18 22:55 UTC, cscharf commented
> Not sure I see the need to keep `http` as well.  Would there ever be a situation where a URI would fail to create with `https` but not `http`?

Some legacy sites don't have https bindings so https may fail but http work

2020-12-18 22:56 UTC, MGibson1 commented
I don't know the URI class well enough to say for sure.

I imaging it just does some semantic checks, but it sees _possible_ it actually makes a call to see if the server responds.

2020-12-18 22:57 UTC, mportune-bw commented
> Some legacy sites don't have https bindings so https may fail but http work

This is just URI creation though, not an actual network request.

2020-12-18 22:58 UTC, MGibson1 commented
> Not sure I see the need to keep `http` as well. Would there ever be a situation where a URI would fail to create with `https` but not `http`?

I don't know the URI class well enough to say for sure.

I imagine it just does some semantic checks, but it sees possible it actually makes a call to see if the server responds.

2020-12-21 15:24 UTC, cscharf requested changes

2020-12-21 15:24 UTC, cscharf commented on src/Android/Accessibility/AccessibilityHelpers.cs
> +                    } else if (Uri.TryCreate("http://" + uri, UriKind.Absolute, out var _))
Please move the `else if` on the next line after the trailing `}`

2020-12-21 15:24 UTC, cscharf commented on src/Android/Accessibility/AccessibilityHelpers.cs
> +                    } else if (Uri.TryCreate("http://" + uri, UriKind.Absolute, out var _))
Also, this `else if` block is not necessary, so you should be able to remove it anyway. If `https://` doesn't work, `http://` won't either when using `Uri.TryCreate()`

2020-12-21 15:43 UTC, cscharf approved these changes

2020-12-21 15:58 UTC, merged