Hide email address in Sends
bitwarden/mobile pull request #1340
Opened 2021-03-26 05:45 UTC by eliykat

## Objective
Allow the creator of a Send to hide their email address from the recipient.

See the [web PR](https://github.com/bitwarden/web/pull/895) and [server PR](https://github.com/bitwarden/server/pull/1234) for more info and discussion.

## Code changes
* add "Hide my email address from recipients" toggle slider to the Send AddEdit page
* check and enforce new Send Options Policy > which can disable this new feature (`disableHideEmail`)
* add banner at the top of the Send AddEdit page if Send Options policy is in effect

## Screenshots

![Screen Shot 2021-03-26 at 3 44 29 pm](https://user-images.githubusercontent.com/31796059/112587912-34d48880-8e4a-11eb-9d09-a218e415a6c2.png)

![Screen Shot 2021-03-26 at 3 44 42 pm](https://user-images.githubusercontent.com/31796059/112587919-3900a600-8e4a-11eb-93e5-653ddbba733f.png)

2021-03-26 13:49 UTC, mportune-bw commented on src/App/Pages/Send/SendAddEditPageViewModel.cs
> +        public bool DisableHideEmail
OCD alert: `DisableHideEmail` and `SendOptionsPolicyInEffect` should be above this section (probably right after `ShowPassword` and before `EditMode`), and `DisableHideEmailControl` should be up even higher (probably right after `ShareOnSave` and before `TypeOptions`)

2021-03-26 13:52 UTC, mportune-bw commented on src/App/Resources/AppResources.resx
> +    <value>One or more organization policies are affecting your Send options.</value>
Strings containing 'Send' should also include the `<comment>` about Send not being translated (see above)

2021-03-26 13:56 UTC, mportune-bw requested changes
Looks good, just a few tweaks needed

2021-03-29 14:20 UTC, mportune-bw approved these changes

2021-03-29 16:01 UTC, merged

2021-05-06 07:58 UTC, nonobio commented
Hi,

As a user, is it already usable ?

Thanks

2021-05-06 12:57 UTC, cscharf commented
> As a user, is it already usable ?

It will be available in the clients as of next week when we plan to do our client deployments. Until then it is not yet usable (unless you're using a Beta client or direct build asset from one of our client `rc` (release candidate) branch builds.

2021-05-06 13:10 UTC, nonobio commented
Thanks. I installed Android Beta and the option is present :) .