Fix for vault timeout not firing on resume
bitwarden/mobile pull request #1775
Opened 2022-02-13 23:04 UTC by mportune-bw

## Type of change
- [X] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective

Fix for vault timeout not firing on app resume in most recent release.  Closes #1772

## Code changes

* **App.xaml.cs:** The [recent change](https://github.com/bitwarden/mobile/pull/1707) to make `UpdateTheme` async resulted in a race condition which allowed `BaseContentPage.SaveActivity()` to execute prior to `VaultTimeoutService.CheckVaultTimeoutAsync()`.  This resulted in the `LastActiveTime` value being reset before it could be compared to the current time, making the app think only a few milliseconds had passed regardless of how long it was in the background.  By checking vault timeout before executing the improved theme update process, we're able to establish the correct elapsed time again.  @fedemkr Let me know if you see any issues with this interfering with the theme updater.

## Testing requirements

Vault timeout should function as expected again.

## Before you submit
- [ ] I have added **unit tests** where it makes sense to do so (encouraged but not required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)

2022-02-13 23:48 UTC, vvolkgang requested changes

2022-02-13 23:48 UTC, vvolkgang commented on src/App/App.xaml.cs
>          private async void ResumedAsync()
Let's take the opportunity to change this to async Task and use the FireAndForget method @fedemkr added in a previous PR, logging exceptions.

2022-02-14 15:34 UTC, fedemkr approved these changes
It shouldn't interfere with the theme update, but just in case let QA know

2022-02-14 16:28 UTC, vvolkgang approved these changes

2022-02-14 16:29 UTC, merged