[SG-702] Tapping Push Notification does not open the account the request is for
bitwarden/mobile pull request #2112
Opened 2022-10-03 17:09 UTC by andrebispo5

## Type of change
- [X] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective

Tapping Push Notification does not take you to account the request is for.

## Code changes

* **file.ext:** Description of what was changed and why

## Screenshots

## Before you submit
- Please check for formatting errors (`dotnet format --verify-no-changes`) (required)
- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2022-10-03 21:13 UTC, fedemkr requested changes

2022-10-03 21:13 UTC, fedemkr commented on src/App/Services/PushNotificationListenerService.cs
> +                LoggerHelper.LogEvenIfCantBeResolved(ex);
If possible inject the `ILogger` and use it instead of the helper

2022-10-03 21:25 UTC, andrebispo5 commented on src/Android/MainActivity.cs
> +            }
Yes, if the app is in the background and the user clicks the notification it won’t pass on `OnCreate` or `NewIntent`

2022-10-04 18:45 UTC, andrebispo5 commented on src/App/Abstractions/IPushNotificationService.cs
> +        void SendLocalNotification(string title, string message, string notificationId, string notificationType, Dictionary<string, string> notificationData = null, int notificationTimeoutMinutes = 0
Did a big rework for this one.

2022-10-04 19:17 UTC, fedemkr requested changes

2022-10-04 19:17 UTC, fedemkr commented on src/App/Models/NotificationData.cs
> +        public string NotificationId { get; set; }
IMHO there is no need to add the prefix "Notification" to the properties given that the class is called notification data so adding the prefix to anything in there is redundant. Or was is confusing on some context?
Also, for now we can leave it as is but in the future if there are notifications that don't require additional data we should extract the `Id` out of this class (which is the only thing required).

2022-10-04 19:17 UTC, fedemkr commented on src/App/Abstractions/IPushNotificationListenerService.cs
> +        Task OnNotificationTapped(string type, BaseNotificationData data);
if I'm not mistaken, `type` is no longer needed

2022-10-06 20:31 UTC, fedemkr approved these changes

2022-10-07 11:06 UTC, merged