[PM-1280] TDE 2FA - approval options navigation
bitwarden/mobile pull request #2646
Opened 2023-07-26 15:04 UTC by andrebispo5

## Type of change
- [ ] Bug fix
- [X] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective

Navigate to device approval options after a successful 2FA authentication.

## Code changes

* **src/App/Pages/Accounts/TwoFactorPageViewModel.cs:** Add logic for TDE flow and action to call when device approval options is needed.
* **iOS Extension:** Add missing action to navigate to device approval options screen.

## Screenshots

https://github.com/bitwarden/mobile/assets/4648522/bb722b65-cb78-4d66-81d4-bd633ca4b46d

## Before you submit
- Please check for formatting errors (`dotnet format --verify-no-changes`) (required)
- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2023-07-26 19:16 UTC, jlf0dev approved these changes

2023-07-26 20:35 UTC, fedemkr requested changes

2023-07-26 20:35 UTC, fedemkr commented on src/App/Pages/Accounts/TwoFactorPageViewModel.cs
> +                else if (decryptOptions.TrustedDeviceOption != null)
⚠️ `decryptOptions` can be `null` afaik, so a null check is needed here.

2023-07-27 15:50 UTC, fedemkr commented on src/App/Pages/Accounts/LoginPasswordlessRequestViewModel.cs
> +        private async Task HandlePasswordlessLogin(PasswordlessLoginResponse response, bool createPendingAdminRequest)
⛏️ Add async suffix:
```suggestion
        private async Task HandlePasswordlessLoginAsync(PasswordlessLoginResponse response, bool createPendingAdminRequest)
```

2023-07-27 16:47 UTC, andrebispo5 commented on src/App/Pages/Accounts/LoginPasswordlessRequestViewModel.cs
> +        private async Task HandlePasswordlessLogin(PasswordlessLoginResponse response, bool createPendingAdminRequest)
resolved by merge

2023-07-27 16:55 UTC, merged