QA-508 - Build app for automation CI
bitwarden/mobile pull request #2705
Opened 2023-08-18 16:28 UTC by ifernandezdiaz

## Type of change
- [ ] Bug fix
- [ ] New feature development
- [X] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective
Our iOS Automation Tests workflow needs .app versions of our app (because .ipa apps can't be installed on Simulated devices).
This PR adds this new build so we can pull the required artifact every time the mobile workflow is triggered.

## Code changes
* **build.yml:** Adding steps to build a `.app` version for our Mobile Automation workflows
* **iOS.Core.csproj:** Adding a new configuration to allow Release builds for `iPhoneSimulator`

## Before you submit
- Please check for formatting errors (`dotnet format --verify-no-changes`) (required)
- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2023-08-18 16:36 UTC, fedemkr requested changes

2023-08-18 16:36 UTC, fedemkr commented on .github/workflows/build.yml
> +          ls ~/Library/Developer/Xcode/Archives
⛏️ Remove this line, not needed for this build

2023-08-18 16:37 UTC, ifernandezdiaz commented
@trmartin4 @bitwarden/dept-devops Is there any objections on merging this to `master` once it is approved?

2023-08-18 19:08 UTC, fedemkr submitted a review, later dismissed

2023-08-22 19:35 UTC, vgrassia requested changes

2023-08-22 19:35 UTC, vgrassia commented on .github/workflows/build.yml
> +          "/p:Configuration=$configuration" "/p:ArchiveOnBuild=true" "/t:`"Build`""
```suggestion
            "/p:Configuration=$configuration" "/p:ArchiveOnBuild=true" "/t:`"Build`""
```

2023-09-06 17:25 UTC, merged