[PM-3551] Expired SSO token cached
bitwarden/mobile pull request #2718
Opened 2023-08-24 09:01 UTC by andrebispo5

## Type of change
- [X] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective

Fix bug where an expired sso token is cached by the mobile browser and the user cannot continue the sso login flow.

## Code changes

When a user cancels the modal, we will start a cached cleared browser session to login.

## Screenshots

## Before you submit
- Please check for formatting errors (`dotnet format --verify-no-changes`) (required)
- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2023-08-24 12:59 UTC, mpbw2 submitted a review, later dismissed

2023-08-28 14:11 UTC, JaredSnider-Bitwarden submitted a review, later dismissed
LGTM!

2023-08-28 15:57 UTC, fedemkr requested changes

2023-08-28 15:57 UTC, fedemkr commented on src/App/Pages/Accounts/LoginSsoPageViewModel.cs
> +        private bool _useEphemeralWebBrowserSession = false;
⛏️ bool is `false` by default.
```suggestion
        private bool _useEphemeralWebBrowserSession;
```

2023-08-29 15:11 UTC, fedemkr approved these changes

2023-09-08 06:48 UTC, merged