[PM-3222] Migration of data from LiteDB to shared pref storage
bitwarden/mobile pull request #2724
Opened 2023-08-25 23:16 UTC by mpbw2

## Type of change
- [ ] Bug fix
- [X] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective

This change performs data migration out of LiteDB and into shared preferences.  It also changes the mobile storage service to default to saving anything new to shared pref storage, and requires specifying keys for LiteDB storage.

## Code changes

* **StateMigrationService:** Added a 5to6 migration block for global and account-specific state values
* **MobileStorageService.cs:** Added a set of LiteDB storage keys to check against when accessing storage.  Also added an inline litedb-to-pref migration on the getter to cover for values that can't be handled cleanly via StateMigration (`accountBiometricIntegrityValid_{userId}_{systemBioIntegrityState}`) and as a catch-all to prevent anything sneaking into liteDB during the transition.
* **BaseContentPage.cs:** Prevent saving last active time without a userId to prevent the orphaned value from re-appearing in storage
* **Constants.cs:** Adjusted key names and removed `NeverDomainsKey`
* **AppIdService:** Removed `anonymousAppId` getter since `appId` is already anonymous
* **CipherService:** Name changes to sync with `Constants` and removal of `SaveNeverDomainAsync` method
* **StateService:** Name changes to sync with `Constants` and removal of `NeverDomains` getter/setter

## Before you submit
- Please check for formatting errors (`dotnet format --verify-no-changes`) (required)
- Please add **unit tests** where it makes sense to do so (encouraged but not required)
- If this change requires a **documentation update** - notify the documentation team
- If this change has particular **deployment requirements** - notify the DevOps team

2023-08-29 13:22 UTC, mpbw2 commented
I'm aware that `StateMigrationService` has grown into a monster, and I'm evaluating a path forward.  It's important that this migration happens sooner than later though.

2023-08-29 17:27 UTC, fedemkr requested changes

2023-08-29 17:27 UTC, fedemkr commented on src/App/Services/MobileStorageService.cs
> +            return result;
🎨 Even though this is totally fine I like it more when the migration stuff is not done in the same place and we can avoid the comment as well given that the method name is self-explanatory, i.e.:
```c#
public async Task<T> GetAsync<T>(string key)
{
    // ...
    return await _preferencesStorageService.GetAsync<T>(key) ?? TryMigrateLiteDBToPrefsAsync(key);
}

private async Task TryMigrateLiteDBToPrefsAsync(string key)
{
    var currentValue = await _liteDbStorageService.GetAsync<T>(key);
    if (currentValue != null)
    {
        await _preferencesStorageService.SaveAsync(key, currentValue);
        await _liteDbStorageService.RemoveAsync(key);
    }
    return currentValue;
}
```
Also it's easier to read on future versions where the path of migration is less likely to happen.
Thoughts?

2023-08-29 17:27 UTC, fedemkr commented on src/App/Services/MobileStorageService.cs
> +        }
❓ `key` will never be null, right?

2023-08-29 17:27 UTC, fedemkr commented on src/Core/Services/StateMigrationService.cs
> +            await SetLastStateVersionAsync(5);
⛏️ Shouldn't this be `6`?
```suggestion
            await SetLastStateVersionAsync(6);
```

2023-08-29 17:27 UTC, fedemkr commented on src/Core/Services/StateMigrationService.cs
> +        }
🤔 Could it happen that the migration at some point fails for some reason and the user starts interacting with the app, which means that the new key/value are going to be stored in `Prefs` and then when the app starts again the migration runs smoothly overriding the last `Prefs` values that the user added with the ones with the old `LiteDB`values? 
E.g. 
v1 of the app has Solarized theme.
v2 of the app has the migration but the theme fails to be migrated for some exception. The user thought changes the theme to Nord.
v3 of the app fixes the migration and when run the theme will be Solarized again which would be wrong I think.

So what I'm getting at is, shall we check first to get the value for the key in `Prefs` and only if that value is `null` set the new value?
```suggestion
        private async Task MoveToPrefsAsync<T>(string key)
        {
            var value = await GetValueAsync<T>(Storage.LiteDb, key);
            if (value == null)
            {
                return;
            }

            if (await GetValueAsync<T>(Storage.Prefs, key) == null)
            {
                await SetValueAsync(Storage.Prefs, key, value);
            }
            await RemoveValueAsync(Storage.LiteDb, key);
        }
```

2023-08-29 17:31 UTC, fedemkr commented
🤔  Regarding the monster migration service I think that having a Chain of responsibility where each version migration has its own file/class would be the best approach. Then we can just stack them in the chain and adding a new migration is as easy as creating a new class and adding it to the stack.

2023-08-29 18:22 UTC, mpbw2 commented on src/App/Services/MobileStorageService.cs
> +        }
Correct!

2023-08-29 18:24 UTC, mpbw2 commented
> 🤔 Regarding the monster migration service I think that having a Chain of responsibility where each version migration has its own file/class would be the best approach. Then we can just stack them in the chain and adding a new migration is as easy as creating a new class and adding it to the stack. Furthermore, we can make all inner things private for each migration class so it's not available from anywhere, not even from the same assembly as it's today.

This is exactly what I want to do. 👍

2023-08-29 18:40 UTC, mpbw2 commented on src/Core/Services/StateMigrationService.cs
> +            await SetLastStateVersionAsync(5);
Yikes, good catch.

2023-08-30 14:54 UTC, fedemkr approved these changes

2023-08-30 14:55 UTC, merged