Send item domain name to fastmail
bitwarden/mobile pull request #2867
Opened 2023-11-12 02:02 UTC by cubemike99

## Type of change
- [ ] Bug fix
- [X] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective
Added a metadata field (forDomain:) to the Fastmail Forwarder API request that's set to the domain name of the item being added to the vault, or to "" if the username generator is being used in standalone mode. This allows the user's Fastmail account to display the domain name for the username that was generated.

## Code changes
- **src/Core/Models/Domain/UsernameGenerationOptions.cs:** `GetForwarderOptions()` will now return a `FastmailForwarderOptions` object with the new `Website` member set to the `EmailWebsite` of `UsernameGenerationOptions` for the fastmail case
- **src/Core/Services/EmailForwarders/FastmailForwarder.cs:** Added the `FastmailForwarderOptions` class that extends `ForwarderOptions` and updated declarations accordingly. Added the `forDomain:` field to the API request
- **src/Core/Services/UsernameGenerationService.cs:** Removed the fastmail case from the switch, and turned it into an if that casts the `ForwarderOptions` to `FastmailForwarderOptions`, mirroring handling of AnonAddy

## Screenshots
A Masked Email entry in Fastmail before the changes for the domain google.com:
image
![281215619-7a499a65-ab41-4294-a934-eaffb3a7bdbd](https://github.com/bitwarden/mobile/assets/16997120/d0a65800-6814-4ef9-a850-87f8af08575b)

A Masked Email entry in Fastmail after the changes for the domain google.com:
image
![281215539-e908bd01-faed-43dc-828a-46f19a6bedae](https://github.com/bitwarden/mobile/assets/16997120/6c271410-e97b-4550-b674-20e434821b54)

## Testing
Tested in the Android emulator and on Android hardware

## Dotnet Format Changes
None found

2023-11-14 21:02 UTC, audrey-jensen requested changes
Hey @cubemike99, thank you for your contribution! 

I have a few  ⛏️ nitpicks, but this change otherwise looks great! I can get this into QA once they're applied and you've verified the code builds. 😄

2023-11-15 00:48 UTC, cubemike99 commented
Thanks for the tips, @audrey-jensen. TIL about null coalescence. As for the second change, I had it your way around at first, then changed it before I committed it 😅.

2023-11-15 23:18 UTC, audrey-jensen commented
> TIL about null coalescence.

Even wilder is that in C# you can combine it with `?.` and `throw`.

```C#
#nullable enable warnings

using System;

var foobar = new Foo { Bar = new Foo() };
Console.WriteLine(foobar?.Bar ?? throw new Exception("Not thrown."));

var foo = new Foo();
Console.WriteLine(foo?.Bar ?? throw new Exception("Thrown!"));

class Foo {
    public Foo? Bar { get; set; }
    override public string ToString() => "NICE";
}
```

This is toy code, but it really shines when you're working in [anti-corruption layers](https://learn.microsoft.com/en-us/azure/architecture/patterns/anti-corruption-layer).

Anyway, thank you for the changes! I'll let our QA team know this code is ready for testing!

2023-11-15 23:39 UTC, audrey-jensen submitted a review, later dismissed

2023-11-17 14:14 UTC, audrey-jensen commented
@cubemike99 - I applied `dotnet format` to your changes. Could you pull the commit into your fork from the qa tracking branch: `community/PM-4800/send-item-domain-to-fastmail`?

Should be something like:
```
git remote add upstream # insert your preferred uri method here
git fetch upstream community/PM-4800/send-item-domain-to-fastmail
git pull upstream community/PM-4800/send-item-domain-to-fastmail
```

2023-11-17 17:11 UTC, audrey-jensen commented
QA Passed! 

Added a hold to the ticket for the formatting update.

2023-11-17 17:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bitwarden/mobile?pullRequest=2867) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/bitwarden/mobile?pullRequest=2867) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: cubemike99<br/>:x: audrey-jensen<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bitwarden/mobile?pullRequest=2867) it.</sub>

2023-11-17 17:21 UTC, cubemike99 commented
Done. Sorry about that. Thanks for catching it.

2023-11-17 18:36 UTC, audrey-jensen approved these changes

2023-11-17 22:17 UTC, audrey-jensen commented
The F-Droid build failure is fixed on `master`. It was caused by a misaligned version of the .Net SDK and JDK. The branch will apply cleanly without it, so this PR is safe to merge.

2023-11-17 22:17 UTC, merged