Steam sign in procedure inside Bitwarden
bitwarden/mobile pull request #573
Opened 2019-08-02 12:32 UTC by tipfom

Using this you can retrieve SteamGuard TOTP codes inside Bitwarden without a rooted Android device or SteamDesktopAuthenticator.
To use it you have to enter "steam" into the TOTP textbox, then a "Sign in with Steam" button appears and you are promted into a dialog that manages the rest.
It isn't yet localized (as I didn't know how to localize it) and its ui may not be final, but it's a good foundation for a work in progress.

Any suggestions welcome :)

2019-08-11 16:34 UTC, Crocmagnon commented
Hi there 👋 could you please provide some screenshots so we can better see what you accomplished? 🙂

2019-08-12 11:12 UTC, tipfom commented
Of course.
When entering "steam" into the TOTP textbox a button appears (https://ibb.co/vh17qnh).
Afterwards you are guided through a sign in process gathering all the required information (https://ibb.co/Wn704LX).
At the end your Steam Sign in Token is added (https://ibb.co/bX4FR2T).
Quite straightforward

2019-08-12 15:11 UTC, vargbeaumont commented
Does this have marketplace verifications? If not is there a way I can manually import my shared key? I use SDA and if I setup the authenticator this way I won't be able to use both SDA and this.

2019-08-14 07:01 UTC, tipfom commented
Yes, you can still user the old way with steam desktop authenticator. It's just a way to import your shared key is you don't want to use SDA. 
Marketplace verifications can also be added of wanted :)

2020-01-02 14:00 UTC, szszoke commented
What is blocking this PR from being completed?

Maybe I could help out.

2020-01-05 15:05 UTC, tipfom commented
> What is blocking this PR from being completed?
> 
> Maybe I could help out.

I'm wondering as well.

2020-01-23 19:03 UTC, frode commented
Any feedback on why this is hanging without any feedback?

2020-03-07 13:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bitwarden/mobile?pullRequest=573) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/bitwarden/mobile?pullRequest=573) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bitwarden/mobile?pullRequest=573) it.</sub>

2020-03-10 18:25 UTC, wieltar commented
*bump* Are there still any plans of merging this any time soon?

2020-03-31 18:19 UTC, Elehiggle commented
This is a great piece of functionality. It would really be a shame to see this go to waste because nobody reviews it for 1 year and then says there are too many conflicts. Please review it :(

2020-05-26 09:58 UTC, ChrisLane commented
Would it not be better to display the "Sign in with Steam" button based on the URI?
Otherwise, this will be a feature that hardly any users become aware of.

2020-05-29 10:25 UTC, tipfom commented
@ChrisLane Yeah, UI can be vastly improved. However, there seems to be no point in putting effort into this right now, as this does not seem to be going to be integrated into the app.

2020-12-30 14:07 UTC, boehs commented
> @ChrisLane Yeah, UI can be vastly improved. However, there seems to be no point in putting effort into this right now, as this does not seem to be going to be integrated into the app.

Could you sign the CLA? who knows, then it might attract more attention https://cla-assistant.io/bitwarden/mobile?pullRequest=573

2021-01-10 23:06 UTC, tipfom commented
I just signed it 😊

2021-04-19 13:52 UTC, luximus-hunter commented
Any progress update on the code review? I'm looking forward for the feature

2021-05-25 18:11 UTC, luximus-hunter commented
Any status update?

2021-05-25 18:47 UTC, boehs commented
> Any status update?

This projects lack of maintainers is absurd

2021-05-25 19:03 UTC, mportune-bw requested changes
Please resolve conflicts

2021-05-25 19:18 UTC, boehs commented
@tgreer-bw, First I would like to thank you and @mportune-bw for coming here and finally giving notice to these PR's. I noticed you disliked my post, and rereading it I understand how you may view it as frustrating to be accused of not maintaining the project. While I think you guys do a wonderful job at adding features and such, I think many of us here are frustrated by the lack of any response for TWO YEARS. 

Since the start of the PR, every two months, someone asked for this to be merged and there was NO communication as to if it had been read, and why it was not being merged. Eventually, the request for review from 30 days ago was ignored until @luximus-hunter somehow brought two of you here. Now, there is merge conflicts, but those were not present 2 years ago. I think all of us want more communication beyond "Please resolve conflicts" after 2 years of no action. This is not the first PR that has gone years without being merged, and I think present and future contributors would like to know why nothing is happening.

2021-05-25 19:22 UTC, luximus-hunter commented
There is no reason to call people out here. People have their own lives outside programming. As much as I want this PR to be accepted and merged, people's personal lives and health are more important. It will be done when it's done. I hope sooner then rather, but it's done when it's done. 😉

2021-05-26 14:40 UTC, luximus-hunter commented
Is the no-root access method still working or is it patched? Just to be sure

2021-06-01 12:45 UTC, luximus-hunter commented
@tipfom I'll mention you in case you didn't see the PR had requested changes 😉.

2nd question, i couldn't see what the status on the marketplace verifications. At indicator on that?

Also, if help is needed with merging, i can also try to take a look at the code. Just let me know with a mention.

2021-06-04 00:17 UTC, eliykat commented
Hi everyone, thanks for your interest in this PR and thanks to @tipfom for the submission.

I've been reviewing community PRs with our Product & Engineering team so that we can action some of these older ones. The team has grown a lot in the last 12 months and so we have some more resources to put towards community engagement. However, this PR is not something we plan to support within the Bitwarden mobile app at this time. We currently provide the `steam://` workaround described [here](https://bitwarden.com/help/article/authenticator-keys/#steam-guard-totps), which is imperfect, but we have to draw a line in how much customisation we provide for a single third-party service. The underlying issue here is that Steam uses non-standard TOTP codes and does not support using other 2FA apps.

Sorry for the bad news folks, I think it's an impressive proof of concept, but not something we can accept for merging.

2021-06-04 00:17 UTC, closed without merging

2021-06-04 02:30 UTC, boehs commented
> Hi everyone, thanks for your interest in this PR and thanks to @tipfom for the submission.
> 
> I've been reviewing community PRs with our Product & Engineering team so that we can action some of these older ones. The team has grown a lot in the last 12 months and so we have some more resources to put towards community engagement. However, this PR is not something we plan to support within the Bitwarden mobile app at this time. We currently provide the `steam://` workaround described [here](https://bitwarden.com/help/article/authenticator-keys/#steam-guard-totps), which is imperfect, but we have to draw a line in how much customisation we provide for a single third-party service. The underlying issue here is that Steam uses non-standard TOTP codes and does not support using other 2FA apps.
> 
> Sorry for the bad news folks, I think it's an impressive proof of concept, but not something we can accept for merging.

Thank you for an explanation!

> have some more resources to put towards community engagement

This is great, thank you.